site_name: Moodle et GeoGebra
pages : 
        - Accueil: 'index.md'
        - Analyse Algèbre: 
                - Pourcentages: 'analyse algèbre - pourcentages.md'
                - Fonctions: 'analyse algèbre - fonctions.md'

